name: Backend CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "22"
          distribution: "zulu"

      - name: Install Google Chrome
        run: |
          $ErrorActionPreference = "Stop"
          $chromeInstallerUrl = "https://dl.google.com/chrome/install/GoogleChromeSetup.exe"
          $chromeInstallerPath = "$env:USERPROFILE\chrome_installer.exe"
          Invoke-WebRequest -Uri $chromeInstallerUrl -OutFile $chromeInstallerPath
          Start-Process -FilePath $chromeInstallerPath -ArgumentList '/silent /install' -Wait
          Remove-Item -Path $chromeInstallerPath

      - name: Install ChromeDriver
        run: |
          $CHROMEDRIVER_VERSION = Invoke-RestMethod -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_win32.zip" -OutFile "chromedriver_win32.zip"
          Expand-Archive -Path "chromedriver_win32.zip" -DestinationPath "$env:ProgramFiles"
          Move-Item -Path "$env:ProgramFiles\chromedriver.exe" -Destination "C:\Windows\System32\chromedriver.exe"

      - name: Verify Google Chrome Installation
        run: |
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version

      - name: Verify ChromeDriver Installation
        run: chromedriver --version

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: target\surefire-reports\
